// <auto-generated />
using System;
using Datacenter.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Datacenter.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724070728_AddDevicePositionUNumberCheck")]
    partial class AddDevicePositionUNumberCheck
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("Datacenter.Api.Models.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromPosition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OperatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToPosition")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("AuditRecords", (string)null);
                });

            modelBuilder.Entity("Datacenter.Api.Models.DevicePosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RackId")
                        .HasColumnType("TEXT");

                    b.Property<int>("UHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RackId", "UNumber")
                        .IsUnique();

                    b.ToTable("DevicePositions", null, t =>
                        {
                            t.HasCheckConstraint("CK_DevicePositions_UNumber", "UNumber >= 1");
                        });
                });

            modelBuilder.Entity("Datacenter.Api.Models.Rack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HeightU")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Power")
                        .HasColumnType("REAL");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.Property<double>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "Code")
                        .IsUnique();

                    b.ToTable("Racks", (string)null);
                });

            modelBuilder.Entity("Datacenter.Api.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Rooms", null, t =>
                        {
                            t.HasCheckConstraint("CK_Rooms_Status", "Status IN ('启用', '停用')");
                        });
                });

            modelBuilder.Entity("Datacenter.Api.Models.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceHeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagementIP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("System")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManagementIP")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Servers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Servers_DeviceHeight", "DeviceHeight >= 1");

                            t.HasCheckConstraint("CK_Servers_OperationalStatus", "OperationalStatus IN ('正常', '异常', '维护')");

                            t.HasCheckConstraint("CK_Servers_PositionStatus", "PositionStatus IN ('未上架', '在架', '已下架')");
                        });
                });

            modelBuilder.Entity("Datacenter.Api.Models.ServerPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("EndU")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RackId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartU")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RackId");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerPositions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ServerPositions_StartU", "StartU >= 1");

                            t.HasCheckConstraint("CK_ServerPositions_Status", "Status IN ('在架', '已下架')");
                        });
                });

            modelBuilder.Entity("Datacenter.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "Role IN ('机房管理员', '运维人员', 'DBA/应用运维人员', '只读查看人员')");
                        });
                });

            modelBuilder.Entity("Datacenter.Api.Models.AuditRecord", b =>
                {
                    b.HasOne("Datacenter.Api.Models.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Datacenter.Api.Models.DevicePosition", b =>
                {
                    b.HasOne("Datacenter.Api.Models.Rack", "Rack")
                        .WithMany()
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rack");
                });

            modelBuilder.Entity("Datacenter.Api.Models.Rack", b =>
                {
                    b.HasOne("Datacenter.Api.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Datacenter.Api.Models.ServerPosition", b =>
                {
                    b.HasOne("Datacenter.Api.Models.Rack", "Rack")
                        .WithMany()
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Datacenter.Api.Models.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rack");

                    b.Navigation("Server");
                });
#pragma warning restore 612, 618
        }
    }
}
